HAI 1.2
I HAS A COWNTR ITZ 1
IM IN YR LOOP UPPIN YR COWNTR TIL BOTH SAEM COWNTR AN 101
I HAS A VAR3 ITZ MOD OF COWNTR AN 3
I HAS A VAR5 ITZ MOD OF COWNTR AN 5
  BOTH OF BOTH SAEM VAR5 AN 0 AN BOTH SAEM VAR3 AN 0
  O RLY?
  YA RLY
  VISIBLE "FIZZBUZZ"
  MEBBE BOTH SAEM VAR3 AN 0
  VISIBLE "FIZZ"
  MEBBE BOTH SAEM VAR5 AN 0
  VISIBLE "BUZZ"
  NO WAI
  VISIBLE COWNTR
  OIC
IM OUTTA YR LOOP
KTHXBYE
